### ISSUE TITLE
Need definition for `TypeVar`

### ISSUE THREAD

**Issue by MilesCranmer** [MasonProtter/InfixUnions.jl#1]
Following up on https://discourse.julialang.org/t/proposed-alias-for-union-types/108205/135?u=milescranmer – I've started trying this out in SymbolicRegression.jl. I ran into an error related to `TypeVar`. Here's the MWE:

```julia
|(t1::Type, t2::Type) = Union{t1,t2}

MyType = let
    @gensym MyType
    @eval struct $(MyType){T<:Number,AY<:(AbstractVector{T}|Nothing)}
        y::AY
        avg_y::(T|Nothing)
    end
    @eval $(MyType)
end
```

(Note the `@eval` business is just so you can keep creating the type `MyType` without needing to restart the REPL.)

This generates the following error:

```julia
ERROR: MethodError: no method matching |(::TypeVar, ::Type{Nothing})

Closest candidates are:
  |(::Type, ::Type)
   @ Main ~/PermaDocuments/SymbolicRegression.jl/src/tmp2.jl:1

Stacktrace:
 [1] top-level scope
   @ ~/PermaDocuments/SymbolicRegression.jl/src/tmp2.jl:7
```

This is because `TypeVar` is **not** `<: Type` (I don't know why that is...). So to fix this it just needs to be modified to:

```julia
|(t1::Union{Type,TypeVar}, t2::Union{Type,TypeVar}) = Union{t1,t2}
```

And then this definition works fine!

**Comment by MasonProtter** [comment]
Good catch!

**Comment by MilesCranmer** [comment]
@MasonProtter do you think you could release a new version in it? Then I can officially add it as a dependency to some packages.

**Comment by MasonProtter** [comment]
Oops!

**Comment by MilesCranmer** [comment]
Thanks!
