### ISSUE TITLE
Nullary operators are aliases for Base.Bottom?

### ISSUE THREAD

**Issue by mkitti** [MasonProtter/InfixUnions.jl#3]
InfixUnions package creates aliases for `Union{}` , also known as `Base.Bottom`, when the operators are used as nullary operators. I'm unsure if that was your intention.

```julia
julia> using InfixUnions

julia> InfixUnions.:|()
Union{}

julia> InfixUnions.:∪()
Union{}

julia> InfixUnions.:∨()
Union{}

julia> ans == Base.Bottom
true
```

This seems a bit unusual to me since there are no types involved. `|()` could have been a boolean or `missing` rather than `Union{}`. Likewise `∪()` could be the empty set, `Set{Any}()`.

If that was not your intention, then you might want the following.
```julia
for op ∈ (:|, :∪, :∨)
    @eval $op(t1::Union{Type, TypeVar}, typs::Union{Type, TypeVar}...) = Union{t1, typs...}
end
```

**Comment by MasonProtter** [comment]
Yeah it was intentional
